language: python
python:
  - "2.7"
  - "3.3"
install:
  - "python setup.py install"
  - "pip install pyyaml ua-parser"
before_script:
            
            - mkdir -p shippable/testresults

script:
  - python -m unittest discover --with-xunit --xunit-file=shippable/testresults/nosetests.xml
